### ISSUE TITLE
ftp.stack.nl no longer exists as a download location

### ISSUE THREAD

**Issue by dhalbert** [adafruit/travis-ci-arduino#32]
https://github.com/adafruit/travis-ci-arduino/blob/master/doxy_gen_and_deploy.sh#L44
```
wget -q ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.13.linux.bin.tar.gz
```
now fails because `ftp.stack.nl` no longer exists.

**Comment by ladyada** [comment]
woops, can you replace with https://cdn-learn.adafruit.com/assets/assets/000/067/405/original/doxygen-1.8.13.linux.bin.tar.gz and re-try?

**Comment by ladyada** [comment]
this is fixed yeah?

**Comment by dhalbert** [comment]
Yes, fixed I was debugging the ESP8266 problems. Arduino libs without ESP8266 build fine in travis; if ESP8266 is included that part of the build still fails.
